### ISSUE TITLE
API key implementation status? And email extraction would be neat

### ISSUE THREAD

**Issue by hnguyenocdtech** [codingatty/Plumage-py#3]
Hi, since Feburary 2020, the USPTO made a mandate to make sure all trademark registrations include the primary email address (most of the time a legal representative) and secondary email address (the one of the registration partner) to be included in the application. Where could I implement this in the module? Thank you so much!! 

Also any updates on the API key implementation? It would be great if you could help me point out how you imagine doing this. Thank you.

**Comment by codingatty** [comment]
I've added API Key support to the pre-release of 1.4.0; have a look at https://github.com/codingatty/Plumage-py/tree/prerelease . It's not final and some things may still change before final; I'm currently updating [Plumage-dotnet](https://github.com/codingatty/Plumage-dotnet) as well, and somethings here may change to avoid inconsistencies that I would otherwise encounter.

In addition to the API key support, changes in this release will include:

- Checks frequency of calls to TSDR to stay within the PTO-enforced limit (60/minute for XML fetches);
- Changes to use ST96 XML text as the default, instead of ZIP files; the PTO limit is more generous (only 4/minute for ZIPs), and the only advantage to the ZIP file is to get the specimen image; you can still get that by overriding;
- Some metadata changes;
- New method GetMetainfo() allowing access to some metadata (that not specific to TSDR) without invoking a TSDR call;
- Methods previously named "unset..." are now consistently "reset..."
- Python 2 no longer supported (Python stopped supporting Python 2 over a year ago, and I no longer have it installed to test with; and when writing the timing support, I found myself using some features that were introduced in Python 3.6)
- Uses what will be the next release of [Plumage-XSL](https://github.com/codingatty/Plumage) (also 1.4.0-pre), adding support to both international and domestic classes.

I'll look into the email extraction support, but it won't be in this release. If you want to get that early, you can create your own XSL file that is email-aware and override the included transforms. I'll have to figure out the best way to handle that. TSDR allows and reports multiple email addresses for a single correspondent (see, e.g. the [TSDR data for application no. 90/449,807](https://tsdr.uspto.gov/#caseNumber=90449807&caseType=SERIAL_NO&searchType=statusSearch)), and Plumage is not designed with multiple field-values in mind. But I'll look into the XML and see if its doable.

**Comment by codingatty** [comment]
Closed per #2
